#remote_theme: pages-themes/architect@v0.2.0
theme: jekyll-theme-architect
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
title: David Ruth ePortfolio
description: SNHU CS499 - Computer Science Capstone
show_downloads: false
